// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/features/home/data/repo.dart/movie_repo_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/core/database/api/api_consumer.dart' as _i2;
import 'package:movies/core/features/home/data/data_source/remote_data_source/movie_remote_data_source.dart'
    as _i4;
import 'package:movies/core/features/home/data/models/movie_detail_model/movie_detail_model.dart'
    as _i3;
import 'package:movies/core/features/home/data/models/movie_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiConsumer_0 extends _i1.SmartFake implements _i2.ApiConsumer {
  _FakeApiConsumer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailModel_1 extends _i1.SmartFake
    implements _i3.MovieDetailModel {
  _FakeMovieDetailModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRemoteDataSourceImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSourceImp extends _i1.Mock
    implements _i4.MovieRemoteDataSourceImp {
  MockMovieRemoteDataSourceImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiConsumer get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeApiConsumer_0(this, Invocation.getter(#api)),
          )
          as _i2.ApiConsumer);

  @override
  _i5.Future<List<_i6.MovieModel>> getPopularMovie() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovie, []),
            returnValue: _i5.Future<List<_i6.MovieModel>>.value(
              <_i6.MovieModel>[],
            ),
          )
          as _i5.Future<List<_i6.MovieModel>>);

  @override
  _i5.Future<List<_i6.MovieModel>> getTopRated() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRated, []),
            returnValue: _i5.Future<List<_i6.MovieModel>>.value(
              <_i6.MovieModel>[],
            ),
          )
          as _i5.Future<List<_i6.MovieModel>>);

  @override
  _i5.Future<List<_i6.MovieModel>> getNowPlaying() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlaying, []),
            returnValue: _i5.Future<List<_i6.MovieModel>>.value(
              <_i6.MovieModel>[],
            ),
          )
          as _i5.Future<List<_i6.MovieModel>>);

  @override
  _i5.Future<_i3.MovieDetailModel> getMovieDetails(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetails, [id]),
            returnValue: _i5.Future<_i3.MovieDetailModel>.value(
              _FakeMovieDetailModel_1(
                this,
                Invocation.method(#getMovieDetails, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.MovieDetailModel>);

  @override
  _i5.Future<List<_i6.MovieModel>> getSimilarMovies(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSimilarMovies, [id]),
            returnValue: _i5.Future<List<_i6.MovieModel>>.value(
              <_i6.MovieModel>[],
            ),
          )
          as _i5.Future<List<_i6.MovieModel>>);

  @override
  _i5.Future<List<_i6.MovieModel>> searchMovies(String? movie) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [movie]),
            returnValue: _i5.Future<List<_i6.MovieModel>>.value(
              <_i6.MovieModel>[],
            ),
          )
          as _i5.Future<List<_i6.MovieModel>>);
}
