// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/features/home/presentation/cubits/movie_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/core/errors/failure.dart' as _i6;
import 'package:movies/core/features/home/data/models/movie_detail_model/movie_detail_model.dart'
    as _i7;
import 'package:movies/core/features/home/domain/repo/movie_repo.dart' as _i2;
import 'package:movies/core/features/home/domain/use_case/movie_details_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepo_0 extends _i1.SmartFake implements _i2.MovieRepo {
  _FakeMovieRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailsUseCase extends _i1.Mock
    implements _i4.MovieDetailsUseCase {
  MockMovieDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepo get movieRepo =>
      (super.noSuchMethod(
            Invocation.getter(#movieRepo),
            returnValue: _FakeMovieRepo_0(this, Invocation.getter(#movieRepo)),
          )
          as _i2.MovieRepo);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.MovieDetailModel>> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.MovieDetailModel>>.value(
                  _FakeEither_1<_i6.Failure, _i7.MovieDetailModel>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.MovieDetailModel>>);
}
