// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/features/home/presentation/views/widgets/film_image_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/core/features/home/domain/use_case/now_playing_use_case.dart'
    as _i2;
import 'package:movies/core/features/home/presentation/cubits/now_playing_cubit/now_playing_move_state.dart'
    as _i3;
import 'package:movies/core/features/home/presentation/cubits/now_playing_cubit/now_Playing_movie_cubit.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNowPlayingUseCase_0 extends _i1.SmartFake
    implements _i2.NowPlayingUseCase {
  _FakeNowPlayingUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNowPlayingMovieState_1 extends _i1.SmartFake
    implements _i3.NowPlayingMovieState {
  _FakeNowPlayingMovieState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NowPlayingMovieCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockNowPlayingMovieCubit extends _i1.Mock
    implements _i4.NowPlayingMovieCubit {
  MockNowPlayingMovieCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NowPlayingUseCase get nowPlayingUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#nowPlayingUseCase),
            returnValue: _FakeNowPlayingUseCase_0(
              this,
              Invocation.getter(#nowPlayingUseCase),
            ),
          )
          as _i2.NowPlayingUseCase);

  @override
  _i3.NowPlayingMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNowPlayingMovieState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.NowPlayingMovieState);

  @override
  _i5.Stream<_i3.NowPlayingMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.NowPlayingMovieState>.empty(),
          )
          as _i5.Stream<_i3.NowPlayingMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void emit(_i3.NowPlayingMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i6.Change<_i3.NowPlayingMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
