// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/features/home/presentation/views/widgets/movie_details_body_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/core/features/home/domain/use_case/get_similar_movies.dart'
    as _i4;
import 'package:movies/core/features/home/domain/use_case/movie_details_use_case.dart'
    as _i2;
import 'package:movies/core/features/home/presentation/cubits/get_similar-movie/similar_movie_cubit.dart'
    as _i9;
import 'package:movies/core/features/home/presentation/cubits/get_similar-movie/similar_movie_state.dart'
    as _i5;
import 'package:movies/core/features/home/presentation/cubits/movie_details_cubit/movie_details_cubit.dart'
    as _i6;
import 'package:movies/core/features/home/presentation/cubits/movie_details_cubit/movie_details_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieDetailsUseCase_0 extends _i1.SmartFake
    implements _i2.MovieDetailsUseCase {
  _FakeMovieDetailsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailsState_1 extends _i1.SmartFake
    implements _i3.MovieDetailsState {
  _FakeMovieDetailsState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSimilarMoviesUseCase_2 extends _i1.SmartFake
    implements _i4.GetSimilarMoviesUseCase {
  _FakeGetSimilarMoviesUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimilarMovieState_3 extends _i1.SmartFake
    implements _i5.SimilarMovieState {
  _FakeSimilarMovieState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieDetailsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailsCubit extends _i1.Mock implements _i6.MovieDetailsCubit {
  MockMovieDetailsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieDetailsUseCase get movieDetailsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#movieDetailsUseCase),
            returnValue: _FakeMovieDetailsUseCase_0(
              this,
              Invocation.getter(#movieDetailsUseCase),
            ),
          )
          as _i2.MovieDetailsUseCase);

  @override
  _i3.MovieDetailsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieDetailsState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.MovieDetailsState);

  @override
  _i7.Stream<_i3.MovieDetailsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.MovieDetailsState>.empty(),
          )
          as _i7.Stream<_i3.MovieDetailsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  dynamic getMovieDetails(int? id) =>
      super.noSuchMethod(Invocation.method(#getMovieDetails, [id]));

  @override
  void emit(_i3.MovieDetailsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i3.MovieDetailsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SimilarMovieCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimilarMovieCubit extends _i1.Mock implements _i9.SimilarMovieCubit {
  MockSimilarMovieCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetSimilarMoviesUseCase get getSimilarMoviesUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getSimilarMoviesUseCase),
            returnValue: _FakeGetSimilarMoviesUseCase_2(
              this,
              Invocation.getter(#getSimilarMoviesUseCase),
            ),
          )
          as _i4.GetSimilarMoviesUseCase);

  @override
  _i5.SimilarMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSimilarMovieState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.SimilarMovieState);

  @override
  _i7.Stream<_i5.SimilarMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.SimilarMovieState>.empty(),
          )
          as _i7.Stream<_i5.SimilarMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  dynamic getSimilarMovies(int? id) =>
      super.noSuchMethod(Invocation.method(#getSimilarMovies, [id]));

  @override
  void emit(_i5.SimilarMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i5.SimilarMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
