// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/features/home/domain/now_playing_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/core/errors/failure.dart' as _i5;
import 'package:movies/core/features/home/data/models/movie_detail_model/movie_detail_model.dart'
    as _i7;
import 'package:movies/core/features/home/data/models/movie_model.dart' as _i8;
import 'package:movies/core/features/home/domain/entitiy/movie_entity.dart'
    as _i6;
import 'package:movies/core/features/home/domain/repo/movie_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepo extends _i1.Mock implements _i3.MovieRepo {
  MockMovieRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>
  getPopularMovie() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovie, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.MovieEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.MovieEntity>>(
                this,
                Invocation.method(#getPopularMovie, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>
  getTopRatedMovie() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovie, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.MovieEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.MovieEntity>>(
                this,
                Invocation.method(#getTopRatedMovie, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>
  getNowPlayingdMovie() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingdMovie, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.MovieEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.MovieEntity>>(
                this,
                Invocation.method(#getNowPlayingdMovie, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetailModel>> getDetailsMovie(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDetailsMovie, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetailModel>>.value(
                  _FakeEither_0<_i5.Failure, _i7.MovieDetailModel>(
                    this,
                    Invocation.method(#getDetailsMovie, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetailModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.MovieModel>>> getSimilarMovies(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSimilarMovies, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i8.MovieModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i8.MovieModel>>(
                    this,
                    Invocation.method(#getSimilarMovies, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.MovieModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.MovieModel>>> searchMovies(
    String? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [movie]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i8.MovieModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i8.MovieModel>>(
                    this,
                    Invocation.method(#searchMovies, [movie]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.MovieModel>>>);
}
